name: Docker Build & Push

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "crates/**"
      - "web/**"
      - "Cargo.toml"
      - "Dockerfile"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DS Arena
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Ghcr Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: elabosak233
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: elabosak233
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/ds-arena
            docker.io/${{ github.repository_owner }}/ds-arena
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref, '-') }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true