name: Docker Build & Push

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "crates/**"
      - "web/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Dockerfile"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DS Arena
        uses: actions/checkout@v4

      - name: Read current version
        id: current
        run: |
          VERSION=$(awk -F '"' '/^\[workspace\.package\]/{f=1} f && /^version *=/{print $2; exit}' Cargo.toml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"

      - name: Read previous version
        id: previous
        run: |
          git fetch origin main --depth=2 || true

          if [ "$(git rev-list --count HEAD)" -lt 2 ]; then
            echo "version=none" >> $GITHUB_OUTPUT
            echo "Only one commit found, skipping previous version check."
          else
            PREV_VERSION=$(git show HEAD~1:Cargo.toml | awk -F '"' '/^\[workspace\.package\]/{f=1} f && /^version *=/{print $2; exit}' || echo "none")
            echo "version=$PREV_VERSION" >> $GITHUB_OUTPUT
            echo "Previous version: $PREV_VERSION"
          fi

      - name: Check if version changed
        id: is_version_changed
        run: |
          if [ "${{ steps.current.outputs.version }}" != "${{ steps.previous.outputs.version }}" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "${{ steps.previous.outputs.version }} â†’ ${{ steps.current.outputs.version }}"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "${{ steps.current.outputs.version }}"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Ghcr Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: elabosak233
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: elabosak233
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Define tags
        id: meta
        run: |
          set -e
          
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGES=(
            "ghcr.io/${REPO_OWNER}/ds-arena"
            "docker.io/elabosak233/ds-arena"
          )
          
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          TAGS=("dev" "${SHORT_SHA}")
          
          if [ "${{ steps.is_version_changed.outputs.changed }}" = "true" ]; then
            VERSION="${{ steps.current.outputs.version }}"
            TAGS+=("${VERSION}" "latest")
          
            if [[ "$VERSION" =~ ^([0-9]+)\.([0-9]+)\.[0-9]+$ ]]; then
                MAJOR="${BASH_REMATCH[1]}"
                MINOR="${BASH_REMATCH[2]}"
                TAGS+=("${MAJOR}.${MINOR}")
            fi
          fi
          
          COMBINED_TAGS=()
          for img in "${IMAGES[@]}"; do
            for tag in "${TAGS[@]}"; do
              COMBINED_TAGS+=("${img}:${tag}")
            done
          done
          
          OUTPUT=$(IFS=, ; echo "${COMBINED_TAGS[*]}")
          echo "tags=$OUTPUT" >> $GITHUB_OUTPUT
          echo "$OUTPUT"

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true